name: Node.js CI - server.mjs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - run: npm install
      - run: node server.mjs
      # - run: npm run build --if-present
      # - run: npm test
